/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts.perpus;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Ridjal Fathoni
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tbJudul = new javax.swing.JTextField();
        tbNo = new javax.swing.JTextField();
        tbNama = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAlamat = new javax.swing.JTextArea();
        rbBaru = new javax.swing.JRadioButton();
        rbLama = new javax.swing.JRadioButton();
        tgl_pinjam = new com.toedter.calendar.JDateChooser();
        tgl_kembali = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btPrint = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel10.setText("PERPUSTAKAAN");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 30, 530, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 930, 100);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 30, 275, 10);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM ISI DATA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 4, 100, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TANGGAL KEMBALI");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 410, 260, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NO ANGGOTA");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 40, 260, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAMA PEMINJAM");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 90, 260, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ALAMAT PEMINJAM");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 140, 260, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("JENIS BUKU");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 270, 260, 20);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("JUDUL BUKU");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 310, 260, 20);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TANGGAL PINJAM");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 360, 260, 20);
        jPanel1.add(tbJudul);
        tbJudul.setBounds(10, 330, 240, 30);
        jPanel1.add(tbNo);
        tbNo.setBounds(10, 60, 240, 30);
        jPanel1.add(tbNama);
        tbNama.setBounds(10, 110, 240, 30);

        tbAlamat.setColumns(20);
        tbAlamat.setRows(5);
        jScrollPane2.setViewportView(tbAlamat);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 160, 240, 110);

        rbBaru.setBackground(null);
        buttonGroup1.add(rbBaru);
        rbBaru.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbBaru.setText("Buku Baru");
        jPanel1.add(rbBaru);
        rbBaru.setBounds(10, 290, 89, 23);

        rbLama.setBackground(null);
        buttonGroup1.add(rbLama);
        rbLama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbLama.setText("Buku Lama");
        jPanel1.add(rbLama);
        rbLama.setBounds(120, 290, 93, 23);
        jPanel1.add(tgl_pinjam);
        tgl_pinjam.setBounds(10, 380, 240, 30);
        jPanel1.add(tgl_kembali);
        tgl_kembali.setBounds(10, 430, 240, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 110, 260, 490);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(null);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(0, 30, 680, 10);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("DATA");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 10, 31, 14);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No Anggota", "NAMA PEMINJAM", "ALAMAT PEMINJAM", "JENIS BUKU", "JUDUL BUKU", "TANGGAL PINJAM", "TANGGAL KEMBALI"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 620, 370);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(270, 170, 650, 440);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(null);

        btPrint.setText("Print");
        jPanel4.add(btPrint);
        btPrint.setBounds(530, 10, 100, 30);

        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        jPanel4.add(btSave);
        btSave.setBounds(10, 10, 100, 30);

        btClear.setText("Clear");
        jPanel4.add(btClear);
        btClear.setBounds(180, 10, 100, 30);

        btDelete.setText("Delete");
        jPanel4.add(btDelete);
        btDelete.setBounds(350, 10, 100, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(270, 110, 640, 50);

        setSize(new java.awt.Dimension(928, 634));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        SimpleDateFormat dateformat = new SimpleDateFormat("yyy-MM-dd");
        String tgl1 = dateformat.format(tgl_pinjam.getDate());
        String tgl2 = dateformat.format(tgl_kembali.getDate());
        String Jenis;
        if(rbBaru.isSelected())
        {
            Jenis = "Buku Baru";
        }
        else {
            Jenis = "Buku Lama";
        }
        
        if ("".equals(tbNo.getText()) || "".equals(tbNama.getText()) || 
            "".equals(tbAlamat.getText()) || Jenis.equals("") || "".equals(tbJudul.getText()) ||
            tgl1.equals("") || tgl2.equals("")) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error",
            JOptionPane.WARNING_MESSAGE);
        } else {
            String SQL ="INSERT INTO tb_peminjam(no,nama,alamat,jenis,judul,tgl_pinjam,tgl_kembali)" +
                        "VALUES('"+tbNo.getText()+"','"+tbNama.getText()+"','"+tbAlamat.getText()+"','"+Jenis+"','"+tbJudul.getText()+"',"
                            + "'"+tgl1+"','"+tgl2+"')";
        }
    }//GEN-LAST:event_btSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btPrint;
    private javax.swing.JButton btSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbBaru;
    private javax.swing.JRadioButton rbLama;
    private javax.swing.JTextArea tbAlamat;
    private javax.swing.JTextField tbJudul;
    private javax.swing.JTextField tbNama;
    private javax.swing.JTextField tbNo;
    private com.toedter.calendar.JDateChooser tgl_kembali;
    private com.toedter.calendar.JDateChooser tgl_pinjam;
    // End of variables declaration//GEN-END:variables
}
