/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts.perpus;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ridjal Fathoni
 */
public class Pengembalian extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public Pengembalian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tbDenda = new javax.swing.JTextField();
        tbNo = new javax.swing.JTextField();
        tbNama = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAlamat = new javax.swing.JTextArea();
        tgl_pinjam = new com.toedter.calendar.JDateChooser();
        cbJenis = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        tgl_kembali = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        tbJudul = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rdT = new javax.swing.JRadioButton();
        rdB = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btPrint = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Bebas", 0, 18)); // NOI18N
        jLabel10.setText("PERPUSTAKAAN");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 0, 530, 30);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Bebas", 0, 18)); // NOI18N
        jLabel11.setText("PEngembalian BUKU ");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 60, 230, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 930, 100);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 30, 275, 10);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM ISI DATA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 4, 100, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NO ANGGOTA");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 40, 260, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAMA PEMINJAM");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 90, 260, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ALAMAT PEMINJAM");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 140, 260, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("JENIS BUKU");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 270, 260, 20);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("JUDUL BUKU");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 320, 260, 20);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TANGGAL PINJAM");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 370, 260, 20);
        jPanel1.add(tbDenda);
        tbDenda.setBounds(10, 490, 240, 30);
        jPanel1.add(tbNo);
        tbNo.setBounds(10, 60, 240, 30);
        jPanel1.add(tbNama);
        tbNama.setBounds(10, 110, 240, 30);

        tbAlamat.setColumns(20);
        tbAlamat.setRows(5);
        jScrollPane2.setViewportView(tbAlamat);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 160, 240, 110);
        jPanel1.add(tgl_pinjam);
        tgl_pinjam.setBounds(10, 390, 240, 30);

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Buku Biografi", "Buku Sejarah", "Buku Novel", "Buku Sekolah" }));
        jPanel1.add(cbJenis);
        cbJenis.setBounds(10, 290, 240, 30);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DENDA");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 470, 260, 20);
        jPanel1.add(tgl_kembali);
        tgl_kembali.setBounds(10, 440, 240, 30);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("TANGGAL KEMBALI");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 420, 260, 20);
        jPanel1.add(tbJudul);
        tbJudul.setBounds(10, 340, 240, 30);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("STATUS");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 520, 260, 20);

        rdT.setBackground(null);
        buttonGroup1.add(rdT);
        rdT.setText("Tepat Waktu");
        jPanel1.add(rdT);
        rdT.setBounds(10, 540, 87, 23);

        rdB.setBackground(null);
        buttonGroup1.add(rdB);
        rdB.setText("Lewat Batas");
        jPanel1.add(rdB);
        rdB.setBounds(130, 540, 85, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 110, 260, 590);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(null);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(0, 30, 680, 10);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("DATA");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 10, 31, 14);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Anggota", "NAMA PEMINJAM", "ALAMAT PEMINJAM", "JENIS BUKU", "JUDUL BUKU", "TANGGAL PINJAM", "TANGGAL KEMBALI", "Denda", "Status"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 620, 470);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(270, 170, 650, 530);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(null);

        btPrint.setText("Print");
        btPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintActionPerformed(evt);
            }
        });
        jPanel4.add(btPrint);
        btPrint.setBounds(530, 10, 100, 30);

        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        jPanel4.add(btSave);
        btSave.setBounds(10, 10, 100, 30);

        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        jPanel4.add(btClear);
        btClear.setBounds(140, 10, 100, 30);

        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btDelete);
        btDelete.setBounds(270, 10, 100, 30);

        btRefresh.setText("Refresh");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });
        jPanel4.add(btRefresh);
        btRefresh.setBounds(400, 10, 100, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(270, 110, 640, 50);

        setSize(new java.awt.Dimension(928, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String tgl1 = dateformat.format(tgl_pinjam.getDate());
        String tgl2 = dateformat.format(tgl_kembali.getDate());
        String Jenis = (String)cbJenis.getSelectedItem();
        String ST = "";
        if (rdT.isSelected()) {
            ST = "Tepat Waktu";
        } else {
            ST = "Lewat Batas";
        }
                
        if ("".equals(tbNo.getText()) || "".equals(tbNama.getText()) || 
            "".equals(tbAlamat.getText()) || Jenis.equals("") || "".equals(tbJudul.getText()) ||
                tgl1.equals("") || tgl2.equals("") || "".equals(tbDenda.getText()) || ST.equals("")) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error",
            JOptionPane.WARNING_MESSAGE);
        } else {
            String SQL ="INSERT INTO tb_peminjam(no,nama,alamat,jenis,judul,tgl_pinjam,tgl_kembali,Denda,Status)" +
                        "VALUES('"+tbNo.getText()+"','"+tbNama.getText()+"','"+tbAlamat.getText()+"','"+Jenis+"','"+tbJudul.getText()+"',"
                            + "'"+tgl1+"','"+tgl2+"','"+tbDenda.getText()+"','"+ST+"')";
        int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btSaveActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
       
        tbNo.setText("");
        tbNama.setText("");
        tbAlamat.setText("");
        cbJenis.setSelectedItem("--");
        tbJudul.setText("");
        tgl_pinjam.setDateFormatString("");
        tgl_kembali.setDateFormatString("");
        tbDenda.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btClearActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        int baris = tblData.getSelectedRow();
        if (baris != - 1) {
            String NO = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_peminjam WHERE no='"+NO+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
        
        selectData();                                       
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintActionPerformed
        MessageFormat header = new MessageFormat("Data Peminjaman Buku");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)     ");
        try {
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btPrintActionPerformed

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        selectData();
    }//GEN-LAST:event_btRefreshActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int baris = tblData.getSelectedRow();
        if(baris != -1) {
            tbNo.setText(tblData.getValueAt(baris, 0).toString());
            tbNama.setText(tblData.getValueAt(baris, 1).toString());
            tbAlamat.setText(tblData.getValueAt(baris,2 ).toString());
            cbJenis.setSelectedItem(tblData.getValueAt(baris, 3).toString());
            tbJudul.setText(tblData.getValueAt(baris, 4).toString());
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date tgl1 = null;
            Date tgl2 = null;
            try {
                tgl1 = date.parse(tblData.getValueAt(baris, 5).toString());
                tgl2 = date.parse(tblData.getValueAt(baris, 6).toString());
            } catch (ParseException ex) {
                Logger.getLogger(Pengembalian.class.getName()).log(Level.SEVERE, null, ex);
            }
            tgl_pinjam.setDate(tgl1);
            tgl_kembali.setDate(tgl2);
            tbDenda.setText(tblData.getValueAt(baris, 7).toString());
            if("Tepat Waktu".equals(tblData.getValueAt(baris, 8).toString())){
                rdT.setSelected(true);
            } else {
                rdB.setSelected(true);
            }
        }
    }//GEN-LAST:event_tblDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btPrint;
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton btSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton rdB;
    private javax.swing.JRadioButton rdT;
    private javax.swing.JTextArea tbAlamat;
    private javax.swing.JTextField tbDenda;
    private javax.swing.JTextField tbJudul;
    private javax.swing.JTextField tbNama;
    private javax.swing.JTextField tbNo;
    private javax.swing.JTable tblData;
    private com.toedter.calendar.JDateChooser tgl_kembali;
    private com.toedter.calendar.JDateChooser tgl_pinjam;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"no","nama","alamat","jenis","judul","tgl_pinjam","tgl_kembali","Denda","Status"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_peminjam";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
                String NO = rs.getString(1);
                String Nama = rs.getString(2);
                String Alamat = rs.getString(3);
                String Jenis = rs.getString(4);
                String Judul = rs.getString(5);
                String Tgl1 = rs.getString(6);
                String Tgl2 = rs.getString(7);
                String Denda = rs.getString(8);
                String Status = "";
                if ("Tepat Waktu".equals(rs.getString(9))) {
                    Status = "Tepat Waktu";
                } else {
                    Status = "Lewat Batas";
                }
                String data[] = {NO,Nama,Alamat,Jenis,Judul,Tgl1,Tgl2,Denda,Status};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pengembalian.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);
    }
}
